### ISSUE TITLE
Unable to Import Data Set

### ISSUE THREAD

**Issue by SteveFeldman** [jshipper/acled-conflict-visualization#5] opened 2016-01-02 19:06 UTC
Hi Jay,

I'm running mysql 5.7.10 as requested in your README. When I originally attempted to import, I received the following error:

ERROR 1148 (42000) at line 1: The used command is not allowed with this MySQL version

I did a little troubleshooting and then started MySQL with the following option:

mysql --local-infile=1

After import, this is what I get:

Query OK, 0 rows affected (0.12 sec)
Records: 0  Deleted: 0  Skipped: 0  Warnings: 0

Essentially no rows are there. I did remove the first two columns as you requested in the CSV. 

If you have a moment to troubleshoot that would be great...

Steve

**Comment by jshipper** [comment] 2016-01-07 04:08
Take a look at the CSV. There may be carriage returns (will look like ^M but the issue is with \r), which may be messing up the import of the file. If so, please replace them with newlines (\n) and try again.

Out of curiosity, what OS are you using? I did my setup in an Ubuntu Server 14.04 VM. Here's how I installed MySQL: https://dev.mysql.com/doc/mysql-apt-repo-quick-guide/en/

**Comment by jshipper** [comment] 2016-01-07 04:25
~~@stevefeldman Correction to above: just remove carriage returns, don't replace them with anything.~~

EDIT 1/9/2016 - Nope, I was right the first time (see below).

**Comment by jshipper** [comment] 2016-01-10 04:43
@SteveFeldman , I made some updates to the README that should address the issue you're having.  I also updated the POJO so that the data file can be used as-is without removing any columns.  I ran through my updated procedure successfully, so I'm hoping it'll work for you too.

Basically, after downloading the data file archive and extracting it, you should just need to replace the carriage returns with new lines (`sed 's/\r/\n/g' ACLED-Version-5-All-Africa-1997-2014_dyadic_Updated_no_notes.csv > ACLED-Version-5-All-Africa-1997-2014_dyadic_Updated_no_notes-modified.csv`) and then re-create the table with the new columns and load the data into the table using the updated CSV file.

Take another stab at importing the data into your MySQL instance and let me know if you are still having problems.  Thanks!

**Comment by jshipper** [comment] 2016-01-19 03:23
@SteveFeldman From what you've told me, I'm closing this issue.  Please reopen if you are still having a problem loading the data.

**Closed as completed by jshipper** 2016-01-19 03:23 UTC
